### ISSUE TITLE
Code release plan

### ISSUE THREAD

**Issue by hangg7** [MoyGcc/vid2avatar#1]
Hi Chen,

Congrats on the amazing work! I am curious if you have any ETA on the first code release.

Best,
Hang

**Comment by MoyGcc** [comment]
Hi Hang,

Thank you! I'm still occupied by the ICCV push and the code needs to be cleaned up afterward. We plan to make it public before the CVPR and probably in April/May.

Best,
Chen

**Comment by hangg7** [comment]
Closing this. Good luck for the ICCV!
