### ISSUE TITLE
Which vertices are used to get index_off_surface?

### ISSUE THREAD

**Issue by xiyichen** [MoyGcc/vid2avatar#10]
Which vertices do `self.mesh_face_vertices` refer to [here](https://github.com/MoyGcc/vid2avatar/blob/094cd1effa38bd372799949c8ab52100bc5ebe7a/code/lib/model/v2a.py#L76), vertices in canonical space or in posed space? If I understand your Opacity Sparseness Regularization correctly, you calculate the distances between the deformed sample points in canonical space and the canonical mesh with current SMPL params, and penalize for rays whose closest sampled point is > 5 cm from the mesh. However, this `self.mesh_face_vertices` comes from `self.smpl_server.verts_c` which is the output of a SMPL forward pass. This confused me as why would you calculate the distance between canonical points and the posed vertices?

**Comment by MoyGcc** [comment]
[Here](https://github.com/MoyGcc/vid2avatar/blob/main/code/lib/model/v2a.py#L61) is where `self.mesh_face_vertices` is initialized and this will be [updated](https://github.com/MoyGcc/vid2avatar/blob/main/code/v2a_model.py#L84) further after several training epochs. So, it's always calculating the distance between canonical points and canonical mesh.
