### ISSUE TITLE
execute problem

### ISSUE THREAD

**Issue by codesoft00** [MoyGcc/vid2avatar#13]
Hi.
My GPU is nvidia 2070, installed torch 1.12.1 + cu11.3 +kaolin 0.13.0 / visual studio 2019
pip install torch==1.12.1 torchvision==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu113
![image](https://github.com/MoyGcc/vid2avatar/assets/89759430/ee0b14d5-03b2-42ea-a6bf-9d17cc09eadb)

All installations succeeded. but, training is fail.
I'm trying to run a training run, but I get the following error:
![캡처1](https://github.com/MoyGcc/vid2avatar/assets/89759430/b8db6de9-42bc-4692-91ea-aca47a778481)
![image](https://github.com/MoyGcc/vid2avatar/assets/89759430/282cf4ed-ef25-41f5-8ec4-126c70102f9a)

I copied the preprocessed demo data to the following location
C:\cg\vid2avatar\data\parkinglot

Before starting the training, I also modified the path setting in metainfo.
![캡처2](https://github.com/MoyGcc/vid2avatar/assets/89759430/e63d2a6f-176c-4acb-82f8-af8b445d83f6)
changed is_continue true.
![image](https://github.com/MoyGcc/vid2avatar/assets/89759430/d1627205-5140-484d-9cfd-8d917e2abd38)

What's the problem?

**Comment by MoyGcc** [comment]
Hi, this might be an OS-dependent issue and especially relates to the installation of pytorch3D on Windows. Can you try to uninstall the pytorch3d and install [in this way](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#2-install-from-a-local-clone) again? Maybe try to follow this instruction strictly and in case you encounter some extra problems, you may find most of the answers in their issues. Sorry, I don't have a Windows PC to debug this.

**Comment by khelkun** [comment]
FYI, I have a similar issue related to pytorch3d after I followed [the instructions](https://github.com/MoyGcc/vid2avatar#getting-started) and installed kaolin 0.10.0. I only tried to run `code/test.py` with the parkinglot demo data:
```
~/vid2avatar/code$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from v2a_model import V2AModel
  File "/home/vizua/vid2avatar/code/v2a_model.py", line 3, in <module>
    from lib.model.v2a import V2A
  File "/home/vizua/vid2avatar/code/lib/model/v2a.py", line 4, in <module>
    from .deformer import SMPLDeformer
  File "/home/vizua/vid2avatar/code/lib/model/deformer.py", line 4, in <module>
    from pytorch3d import ops
  File "/home/vizua/anaconda3/envs/v2a/lib/python3.7/site-packages/pytorch3d/ops/__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "/home/vizua/anaconda3/envs/v2a/lib/python3.7/site-packages/pytorch3d/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```
I'll try to manually install pytorch3d as you suggested @MoyGcc. Also [This pytorch3d issue](https://github.com/facebookresearch/pytorch3d/issues/1406) and the related ones may be helpful though.

A few relevant details:
- I'm on Ubuntu 20.04 with an NVIDIA Tesla 4 and CUDA 11.1.  
- Installed pytorch3d version is pytorch3d-0.7.4 during the `pip install -r requirement.txt`.
- `pip install -r requirement.txt` ran without noticeable errors
- `python setup.py develop` in `code` folder ran without noticeable errors although the installed package name is `UNKNOWN`:
```
~/vid2avatar/code$ python setup.py develop
running develop
/home/vizua/anaconda3/envs/v2a/lib/python3.7/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/home/vizua/anaconda3/envs/v2a/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/lib/libmise/mise.cpython-37m-x86_64-linux-gnu.so -> lib/libmise
Creating /home/vizua/anaconda3/envs/v2a/lib/python3.7/site-packages/UNKNOWN.egg-link (link to .)
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed /home/vizua/vid2avatar/code
Processing dependencies for UNKNOWN==0.0.0
Finished processing dependencies for UNKNOWN==0.0.0
```

I can provide more details

**Comment by khelkun** [comment]
According to [this post](https://github.com/facebookresearch/hydra/issues/2010), upgrading to `hydra-core==1.3.2` did get rid of this hydra error:
```
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/vizua/anaconda3/envs/v2a/lib/python3.7/site-packages/hydra/_internal/utils.py", line 252, in run_and_report
    assert mdl is not None
AssertionError
```

According to [this post](https://discuss.pytorch.org/t/error-in-magma-getdevice-arch-magma-not-initialized-call-magma-init-first-or-bad-device/136735) I tried to fix the magma error by upgrading `pytorch` and `pytorchlighting`:
```
torch==1.10.1+cu111
torchvision==0.11.2+cu111
pytorch-lightning==1.9.5
```
To achieve this upgrade for CUDA 11.1, I had to follow [this pytorch doc](https://pytorch.org/get-started/previous-versions/) and run:
```
pip install -r requirements.txt -f https://download.pytorch.org/whl/cu111/torch_stable.html
```

After that, I needed to:
- rebuild `pytorch3d` :
```
pip uninstall pytorch3d
pip install -r requirements.txt
```
- rebuild kaloin
```
cd kaolin
rm -R build
python setup.py develop
```
- Run again the vid2avatar setup (to be sure):
```
cd ../code
python setup.py develop
```

From there, running `python train.py` goes without printing the `Error in magma_getdevice_arch: MAGMA not initialized (call magma_init() first) or bad device`.  
But I still get the final:
```
  File "lib/libmise/mise.pyx", line 164, in lib.libmise.mise.MISE.to_dense
    assert(not isnan(out_view[i, j, k]))
AssertionError
```
But this occurs during the `training_epoch_end` after "Epoch 20" and I can tell that the `points` array after the loop in `generate_mesh` contains 35937 entries with the expected `point.loc` coordinates but the `point.value` is always `nan.`

**Comment by codesoft00** [comment]
Thanks for your answer. As you said, I uninstalled pytorch3d and reinstalled the requirements, but the following error occurs.

![캡처3](https://github.com/MoyGcc/vid2avatar/assets/89759430/d649a588-05c9-4e80-ac52-0dafcb87916c)
![캡처4](https://github.com/MoyGcc/vid2avatar/assets/89759430/68a3836e-cba9-4ac8-893d-48d139012107)

**Comment by codesoft00** [comment]
Thanks for your answer. As you said, I uninstalled pytorch3d and reinstalled the requirements, but the following error occurs.

![캡처3](https://github.com/MoyGcc/vid2avatar/assets/89759430/bcf19d81-7c71-478a-8d89-f127599d5be2)
![캡처4](https://github.com/MoyGcc/vid2avatar/assets/89759430/3c5e0c62-bcf4-4154-89e0-41c3fa71fb07)
