### ISSUE TITLE
Render SMPL mesh using transformed/normalized parameters

### ISSUE THREAD

**Issue by tiangexiang** [MoyGcc/vid2avatar#23]
Wonderful work!
I am trying to render the SMPL mesh along the training process to see their updates. Instead of using volumetric rendering, I am using the same pytorch3d renderer that you used during preprocessing. The only difference is that the rendering you have done at the 'refined' stage during preprocessing relied on unnormalized parameters. However, when I try to render SMPL mesh by using the normalized parameters (cameras, translation) the mesh is a bit off:
![h36m_rendering](https://github.com/MoyGcc/vid2avatar/assets/67831103/ef219bbd-b059-4c4c-9d0a-1465908fad17)

My workflow is simple: 
1. fetch cameras from 'cameras_normalize.npz', SMPL poses from 'poses.npy', and translation from 'normalize_trans.npy';
2. unpack K, E, and scale from normalized cameras to initialize renderer;
3. use SMPL to get the mesh and apply scale to both vertices and trans.
The above rendering is what I got. Any suggestion is highly appreciated! Thank you!

**Comment by MoyGcc** [comment]
Hi, thank you for your interest. The updated SMPL is always stored in `self.body_model_params` and you could try to fetch the parameters there for SMPL visualization during the update. There are two places (https://github.com/MoyGcc/vid2avatar/blob/main/code/lib/model/smpl.py#L80, https://github.com/MoyGcc/vid2avatar/blob/main/code/lib/datasets/dataset.py#L48) to where you can refer and to have an idea of the SMPL and camera transformation as well as scaling. 

The way you listed should in principle work. Could you double-check the individual steps?

**Comment by tiangexiang** [comment]
Thank you so much for your swift reply! I have found the issue, it could be the inconsistency for pytorch3d renderer that the x-axis of translation should be of the opposite sign. I am now able to render correct SMPL mesh. Thanks!
