### ISSUE TITLE
Can't initialized the environment with given versions

### ISSUE THREAD

**Issue by leobcc** [MoyGcc/vid2avatar#32]
I have been trying to set up the environment as indicated in the README in order to reproduce the results, but I've encountered different conflicts/problems. 
The main issue is that I find the versions torch==1.9.1, and torchvision==0.10.1 to be not available for installation. Installing later releases produces conflicts and errors such as the following two:

ModuleNotFoundError: No module named 'torchtext.legacy

OSError: /usr/local/lib/python3.10/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

I may be getting something wrong but I spent a while trying to figure out versions that would work and thought asking may provide a quicker solution. 
Thank you in advance for your support and availability.

**Comment by MoyGcc** [comment]
Hi, would this probably help you https://github.com/MoyGcc/vid2avatar/issues/12? Let me know if you still have problems with the installation.
