### ISSUE TITLE
Question: Can this be used in real time applications?

### ISSUE THREAD

**Issue by happycr** [MoyGcc/vid2avatar#37]
First of all, I just wanted to say that I love this tool: it's super accurate and realistic compared to everything else I've seen.
Can this be used in real time applications? If not, are there any plans to enable this?

Many Thanks.

**Comment by MoyGcc** [comment]
Hi, thank you for your kind words. Now, the method is a bit far away from being applied in real time. On the one hand, it's basically a pure research project and the code hasn't been optimized for real-time applications. On the other hand, the architecture of the framework doesn't allow in principle super fast training and real-time inference. The algorithm itself still needs to be refined and improved for speed purposes. But I believe maybe there are already research teams in the world working towards this direction. One related work from our group is [InstantAvatar](https://github.com/tijiang13/InstantAvatar) which allows super fast training and rendering during test.

**Comment by happycr** [comment]
Hi, thank you for kindly answering my question for your reference to InstantAvatar. I wish you all the best for the continuation of the project. I have now closed the issue.
