### ISSUE TITLE
ImportError: cannot import name 'mise' from 'lib.libmise' (unknown location)

### ISSUE THREAD

**Issue by wangyichen191** [MoyGcc/vid2avatar#38]
When I run the command **python train.py** or **python test.py**, I get some errors:
<img width="771" alt="截屏2023-07-17 15 06 42" src="https://github.com/MoyGcc/vid2avatar/assets/76057644/ec41477a-bb2c-40ca-9a83-895d8fa88117">
I think this error is related to the use of C++. How could I solve it?

**Comment by MoyGcc** [comment]
Seems like you haven't installed MISE properly. Have you tried `cd code; python setup.py develop`. You expect to find the `.so` file in `vid2avatar/code/lib/libmise`
