### ISSUE TITLE
Would it work on still images

### ISSUE THREAD

**Issue by PrasoonDhapola** [MoyGcc/vid2avatar#4]
Hi, I have possibly the most unsophisticated and silly question. Can this model create avatar form a single image as well? Apologies, if this was too silly for you to answer. but it's a genuine question. Thanks in advance.

**Comment by MoyGcc** [comment]
Hi, this work is a video-based reconstruction approach and thus not applicable for a single image input.

**Comment by carlosedubarreto** [comment]
@PrasoonDhapola  for single image, you could try ECON https://github.com/YuliangXiu/ECON/

**Comment by PrasoonDhapola** [comment]
Thanks for letting me know @MoyGcc and @carlosedubarreto. Apprectiate it!

**Comment by MoyGcc** [comment]
You're welcome. Closing this issue.
