### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by carlosedubarreto** [MoyGcc/vid2avatar#5]
Do you know what is the memory requirements to train and test it?
I was trying and received an memory error
![image](https://user-images.githubusercontent.com/4061130/235362442-f165533f-72b9-46c0-a01c-ea69801c9ab6.png)

I have a RTX 3090 24gb VRAM running on windows.

And, anyway is there some settings that we could try to make it use less memory, to be able to run on our cards?

Thanks a lot!

**Comment by MoyGcc** [comment]
Hi, I also use RTX 3090 with 24 GB. Here is a screenshot of the used memory on my local PC. I haven't tested my code on a Windows system and maybe the memory problem relates to the operating system. To further reduce the memory usage, you could try to decrease the [sampled pixels per each iter](https://github.com/MoyGcc/vid2avatar/blob/main/code/confs/dataset/video.yaml#L15). By default, it's 512 which is already a relatively small number.

![gpu_mem](https://user-images.githubusercontent.com/29098423/235363860-77f8cc6d-55a2-42be-80f1-a9761705a2b6.png)

**Comment by carlosedubarreto** [comment]
Interesting. Thanks I'll try that and report here.

Just let me ask acouple of things.
1- even using the provided dataset I must train using that dataset first right? And that is what takes about 24-48h to finish?

2-the result are a sequence of meshes for each frame of the video? I mean is it possible to use the result to import in Blender?

thanks a lot

**Comment by carlosedubarreto** [comment]
depreasing to 256 made it work

![image](https://user-images.githubusercontent.com/4061130/235364940-eebf0e10-c65f-43de-a36b-715d1e0d3e35.png)

But that is so odd, its just using 5gb of VRAM
![image](https://user-images.githubusercontent.com/4061130/235364970-c60b2e7b-efe6-4097-b3a6-a69351b92856.png)

**Comment by MoyGcc** [comment]
> Interesting. Thanks I'll try that and report here.
> 
> Just let me ask acouple of things. 1- even using the provided dataset I must train using that dataset first right? And that is what takes about 24-48h to finish?
> 
> 2-the result are a sequence of meshes for each frame of the video? I mean is it possible to use the result to import in Blender?
> 
> thanks a lot

1- yes, but I can also provide pre-trained checkpoints if you just want to see the results once fully trained. Here you go: https://drive.google.com/drive/folders/1YGQkYD9wcr_8awv_zjZL0_e7actHKcyf?usp=share_link
2- yes, in the end, you can get all outputs (incl. meshes in .ply format) by simply running `python test.py`. Indeed, the corresponding refined SMPL parameters can also be obtained by extracting from the checkpoints which contain the jointly refined SMPL poses if you also need a skeleton.

**Comment by MoyGcc** [comment]
> depreasing to 256 made it work
> 
> ![image](https://user-images.githubusercontent.com/4061130/235364940-eebf0e10-c65f-43de-a36b-715d1e0d3e35.png)
> 
> But that is so odd, its just using 5gb of VRAM ![image](https://user-images.githubusercontent.com/4061130/235364970-c60b2e7b-efe6-4097-b3a6-a69351b92856.png)

Yes, might be possible. But not sure how the performance will be in the case of 256 samples per iter. I will investigate it a bit when I have more spare time. Before release, I already asked some of my colleagues to try it out and it works well on their machines (24 GB, but all Ubuntu). This memory issue is indeed quite weird.

**Comment by carlosedubarreto** [comment]
Thanks a lot, I'll try the checkpoint provided. and if you allow me to suggest, it would be great to have this checkpoint on the documentation, so more people can test it too.

In my humble opinion 😀

But thanks a lot anyway for providing it to me, and thanks for the explanation.

**Comment by carlosedubarreto** [comment]
Just wrap the subject up. running the full code , when testing (with it generating all the data, mesh, normal masp, masks and etc) I could not use the resolution 512, I had to reduce it to 256 and the VRAM consuption was more than 17gb 

![image](https://user-images.githubusercontent.com/4061130/235436831-d2e5d220-b480-4b0f-9b57-dff08da691b3.png)

**Comment by freezecook** [comment]
I'm having a similar issue. However, I'm using an RTX 3050 with 8 GB VRAM. Reducing the sampled pixels doesn't seem to work in my case.
