### ISSUE TITLE
batch_size: 2 error

### ISSUE THREAD

**Issue by shuochen365** [MoyGcc/vid2avatar#55]
Hello!
what is the problem and how can i solve it ? Thank you !
when I set batch_size: 2 in the train stage, I get this error:
RuntimeError: stack expects each tensor to be equal size, but got [34] at entry 0 and [40] at entry 1

**Comment by MoyGcc** [comment]
Hi, we currently don't support training with batch_size > 1 (one training image per iteration). There should be some NeRF works/codes that use multiple images for one training iteration and you could modify the code based on these resources.

**Comment by shuochen365** [comment]
OK, thank you
