### ISSUE TITLE
 dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by carlosedubarreto** [MoyGcc/vid2avatar#6]
After making it run, I recevided this error
" dtype mismatch, expected 'long' but got 'long long'"

here is the screen
![image](https://user-images.githubusercontent.com/4061130/235366830-dd9487f9-6ab1-45a4-8bd3-f6c037097ad1.png)

Do you have an idea how to fix that?
Thanks
BTW I'm on windows

**Comment by MoyGcc** [comment]
I think this is again a platform-dependent issue. I can try to modify the code according to this PR afterward https://github.com/autonomousvision/differentiable_volumetric_rendering/pull/22.

**Comment by carlosedubarreto** [comment]
I'll try and I'll post the result, thanks

**Comment by carlosedubarreto** [comment]
The link helpd me and also this one

https://github.com/pyansys/pymapdl/issues/14#issuecomment-364654285

In the end, the change that worked for me was this one I attached to this post

[mise.zip](https://github.com/MoyGcc/vid2avatar/files/11362300/mise.zip)
