### ISSUE TITLE
Poor results on PeopleSnapshot dataset

### ISSUE THREAD

**Issue by janehwu** [MoyGcc/vid2avatar#61]
Hi!

I'm trying to run your method on the [PeopleSnapshot dataset](https://graphics.tu-bs.de/people-snapshot). Since the cameras in that dataset are fixed at the origin with no rotation (while the person moves), I had to modify your sphere intersection code since it assumes that the scene is centered at the origin. I also didn't normalize the camera parameters (since there's no rot/trans) and set `sdf_bounding_sphere=1.0` everywhere.

Would you be able to help me debug the results I'm seeing? It looks like the camera and geometry are in the correct locations (otherwise I wouldn't see anything in the render), but there's definitely something I'm doing wrong. Thank you!

The predicted mesh for 1 frame after 100 epochs looks like:
<img src="https://github.com/MoyGcc/vid2avatar/assets/9442165/142c68d6-5a27-4122-8b19-81c38bb5dffa" height="300">

The predicted (foreground) render, mask, and normals are:
<p float="left">
<img src="https://github.com/MoyGcc/vid2avatar/assets/9442165/8ff00cb3-4fef-4499-943d-527293abf9d7" height="200">
<img src="https://github.com/MoyGcc/vid2avatar/assets/9442165/e672c6b6-0913-45e1-948e-b213761f4f9d" height="200">
<img src="https://github.com/MoyGcc/vid2avatar/assets/9442165/c64f97da-d23b-4588-90a7-11df974c05a1" height="200">
</p>

**Comment by MoyGcc** [comment]
Hi,

I just quickly tried vid2avatar on the same sequence you showed and it looks fine to me (as we also tested on PeopleSnapShot before). The screenshot I attached is the canonical mesh after training for 50 epochs.

You could simply follow the preprocessing code to process the data (incl. camera normalization). If you want to fix the camera position, you could try replacing https://github.com/MoyGcc/vid2avatar/blob/main/preprocessing/preprocessing.py#L230 with the following code segment. It means we only normalize once for the first frame and afterward we follow the same normalization shift. That should work out.
```
            if idx == 0:
                v_max = smpl_verts.max(axis=0)
                v_min = smpl_verts.min(axis=0)
                normalize_shift = -(v_max + v_min) / 2.
```
![Screenshot from 2023-11-28 10-38-51](https://github.com/MoyGcc/vid2avatar/assets/29098423/86931fdb-91c9-42cd-8d5e-1cc9d2332e35)
