### ISSUE TITLE
Demo Frame Skip

### ISSUE THREAD

**Issue by GloryyrolG** [MoyGcc/vid2avatar#65]
Hi @MoyGcc @tijiang13 et al.,

May I know the `frame skip` of the provided `parkinglot` demo pls and the recommended value? Thx & rgds,

**Comment by MoyGcc** [comment]
Hi, you can refer to [NeuMan](https://github.com/apple/ml-neuman) repo for more details about the train/val/test split. You can find the splits for `parkinglot` below:  
[val_split.txt](https://github.com/MoyGcc/vid2avatar/files/14452741/val_split.txt)
[train_split.txt](https://github.com/MoyGcc/vid2avatar/files/14452742/train_split.txt)
[test_split.txt](https://github.com/MoyGcc/vid2avatar/files/14452743/test_split.txt)
