### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by carlosedubarreto** [MoyGcc/vid2avatar#7]
I'm having this problem now, but I'm already researching about it. Just opened an issue to leave as reference for others having the same problem
![image](https://user-images.githubusercontent.com/4061130/235376044-ca1151f8-d5e0-4370-b16a-b6bc02801d6c.png)

**Comment by carlosedubarreto** [comment]
The tests I did could not solve the problem, @MoyGcc , do you have any Idea of what I could do?

thanks a lot for all the help.
BTW, even with that problem, I could have the mesh. To create all the mesehs I just commented the part that was giving error, this part
![image](https://user-images.githubusercontent.com/4061130/235379015-80db6b92-471c-4c76-80c9-2c325f589431.png)

**Comment by MoyGcc** [comment]
It was my mistake. I tried to upgrade pytorch-lightning and it seems like the upgrade can accelerate the training process but also introduce bugs. Can you try to downgrade pytorch-lightning `pip install pytorch-lightning==1.5.7`?

**Comment by carlosedubarreto** [comment]
Great thanks, I'll test it now.

**Comment by carlosedubarreto** [comment]
Its working now, thanks.
Its very slow, but its working 😊

![image](https://user-images.githubusercontent.com/4061130/235436948-4be768ec-4447-48bb-b219-d5914822be3e.png)

**Comment by MoyGcc** [comment]
Yes, the inference is slow but it's still more or less 2 minutes on my end... Hopefully, we can bring a faster version soon as well 👍

![image](https://user-images.githubusercontent.com/29098423/235437506-ae1bb8cc-9987-41a3-a5c0-444ab0428fca.png)

**Comment by carlosedubarreto** [comment]
LOL, here is taking almost 20 minutes to execute 4 frames 😅
But the mesh generations only tood about 6 minutes to do it all for the demo scene.
